Changes related mostly to meeting attendants:
mblajek/Memo pull request #208
Opened 2024-01-26 19:39 UTC by TPReal

- Changed the meeting tabes on staff/client details to use the attendants tquery.
- Updated the UI for attendance statuses to support the new statuses system.
- Various UI updates related to meetings.

The backend changes are from other PRs, no need to review.

2024-01-26 20:08 UTC, atryda12 requested changes

2024-01-26 20:08 UTC, atryda12 commented on resources/js/features/meeting/meeting_tables.tsx
> +              infoIcon
Typ się nie zgadza (infoIcon nadmiarowe chyba).

2024-01-26 20:26 UTC, TPReal commented on resources/js/features/meeting/meeting_tables.tsx
> +              infoIcon
Done.

2024-01-26 20:31 UTC, TPReal commented on resources/js/components/ui/calendar/calendar-columns/events.tsx
> +        {" "}
Chyba nie, bo po pierwsze to może tu zawijać, po drugie to jest jakiś standardowy sposób wsadzania spacji (prettier sam takie tworzy jak mu wyjdzie że jest spacja na końcu linii), a po trzecie napisanie zwykłego &nbsp; nie zadziała, nawet nie wiem jak wstawić nbsp w JSX.

2024-01-27 13:45 UTC, atryda12 approved these changes

2024-01-27 15:39 UTC, merged