Draft: FZ-77 add checkbox based on Zag
mblajek/Memo pull request #54
Opened 2023-08-19 16:37 UTC by srflp

WIP 🚧

2023-08-29 11:09 UTC, srflp commented
Wracając do tematu checkboxa z zaga.
Coś jest nie tak z zagiem chyba.

Robię sobie w tym controlledCheckboxie w przeglądarce `$('input[name="controlledCheckbox"]').click()`

Działa, felte i zag załapał, że checkbox jest zaznaczony.

Natomiast gdy z wnętrza Checkboxa wywołam sobie `api().setChecked(machineProps.checked());` to Zag wie, że Checkbox został zaznaczony, ale Felte nie wie, a powinien wiedzieć, bo setCheck wysyła pod spodem event onClick do inputa. Badam sprawę, czemu felte go nie łapie.

Bo powinno działać, tylko w zagu coś skopane pewnie.

2023-08-29 21:09 UTC, TPReal requested changes

2023-08-29 21:09 UTC, TPReal commented on resources/js/components/ui/form/Checkbox.tsx
> +    api().setChecked(inputProps.checked);
Tak chyba nie możesz zrobić. Trzeba pozwolić felte zarządzać tym stanem a nie jakimś propsom.

Ja to bym w ogóle sugerował zrobić to przez createField, wtedy się nie martwisz jakimiś typami eventów i czymś, tylko po prostu implementujesz ten adapter. Chociaż fakt że piszą że jeśli na dole jest natywna kontrolka to powinno to działać z felte.

2023-08-29 21:09 UTC, TPReal commented on resources/js/components/ui/form/Checkbox.tsx
> +  onChange?: checkbox.Context["onChange"];
To chyba powinnno również wylecieć (tak jak checked o którym piszę niżej ale wcześniej). Jak ktoś chce reagować na zmiany to powinien sobie zrobić effect na odpowiednią część felte forma, zgodnie z tym co mówiliśmy na discordzie.

2023-08-29 21:09 UTC, TPReal commented on resources/js/components/ui/form/Checkbox.tsx
> +  indeterminate?: boolean;
To bym wywalił na razie, bo tak samo - tym powinien zajmować się felte. Albo pozwala tristate checkbox albo nie, ale to jego rzecz zarządzać stanem, a tu najwyżej można jego stan tłumaczyć na stan checkboxa.

2023-08-29 21:09 UTC, TPReal commented on resources/js/components/ui/form/Checkbox.tsx
> +  disabled?: boolean;
A tego nie ma w tym typie z którego dziedziczysz te propsy przypadkiem? Bo te TextFieldy to nie biorą disabled explicite tylko właśnie dziedzicząc.

2023-08-30 08:03 UTC, TPReal requested changes

2023-08-30 08:03 UTC, TPReal commented on resources/js/components/ui/form/Checkbox.tsx
> +  checked?: Accessor<boolean>;
Nie no, ta ostatnia zmiana jest w ogóle w złą stronę. Nie możesz podawać sygnału sterującego tym checkboxem bo on już ma sygnał sterujący, z formularza. Popatrz na TextField, tam jest tylko name i label, i standardowe propsy elementu, tu powinno być tak samo.

2023-08-31 18:38 UTC, srflp commented on resources/js/components/ui/form/Checkbox.tsx
> +
Komponenty zawierające hooki to nie są typowe czyste funkcje, które robią jedną rzecz. 

Często każdy kolejny statement ma się nijak do poprzednich. 

Tak plus/minus grupuję ze sobą tylko te linie, w których statementy są ze sobą powiązane, ale coś postaram się pousuwać.

2023-11-13 20:27 UTC, closed without merging